FROM almalinux:9
ENV course="Devops with AWS" \
    trainer="sivakumar" \
    student="sriteja" \
    duration="120HRS"
    # varible will gt replaced
RUN echo "Hi ${student}" > /tmp/test1.txt
CMD ["sleep" , "10s0"]